# Generated by Django 4.1.7 on 2023-04-10 15:02

from django.db import migrations
import utilities.fields


class Migration(migrations.Migration):

    dependencies = [
        ('circuits', '0041_standardize_description_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='circuittype',
            name='color',
            field=utilities.fields.ColorField(default='9e9e9e', max_length=6),
        ),
    ]
